# Config for the Gemini Pull Request Review Bot.
# https://github.com/marketplace/gemini-code-assist
have_fun: false
code_review:
  disable: false
  comment_severity_threshold: 'MEDIUM' # Changed from HIGH to MEDIUM
  max_review_comments: 20 # Changed from -1 to 20
  pull_request_opened:
    help: false
    summary: true
    code_review: true
ignore_patterns:
  - '**/*.md'
  - '**/package-lock.json'
  - '**/dist/'
